version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.3
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"


# version: '3.7'

# services:
#   logstash:
#     build:
#       context: .  # Assumes Dockerfile is in the same directory as docker-compose.yml
#       dockerfile: Dockerfile  # Optional if your Dockerfile has a different name
#     image: logstash-custom:8.15.3  # Custom image name
#     volumes:
#       - ./pipeline:/usr/share/logstash/pipeline  # Mount custom pipeline directory
#       - ./config:/usr/share/logstash/config  # Mount custom config directory
#     ports:
#       - "5044:5044"  # Example for Logstash input port (adjust as necessary)
#     environment:
#       - LOGSTASH_HOME=/usr/share/logstash
